# Generated by Django 4.2.20 on 2025-04-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_stream_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
